name: flutter_butler_flutter
description: Flutter Butler - Your AI-powered personal assistant built with Flutter and Serverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_butler_client:
    path: ../flutter_butler_client
  serverpod_flutter: 3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=3.0.0 <7.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
