# Configuration file for passwords in development.
# IMPORTANT: Do not commit this file to version control with real passwords.

development:
  database: 'password'
  redis: ''

staging:
  database: 'password'
  redis: ''

production:
  database: 'password'
  redis: ''
