# Configuration file for the production environment.

apiServer:
  port: 8080
  publicHost: localhost
  publicPort: 8080
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: localhost
  publicPort: 8081
  publicScheme: https

webServer:
  port: 8082
  publicHost: localhost
  publicPort: 8082
  publicScheme: https

database:
  host: localhost
  port: 5432
  name: flutter_butler
  user: postgres

redis:
  enabled: false
  host: localhost
  port: 6379
