name: flutter_butler_server
description: Flutter Butler - A personal assistant server powered by Serverpod.
version: 1.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod: 3.3.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.3.1
  test: ^1.25.5

serverpod:
  scripts:
    start: dart bin/main.dart --apply-migrations
    flutter_build:
      posix: |
        cd ../flutter_butler_flutter
        flutter build web --base-href /app/ --wasm --output ../flutter_butler_server/web/app
